"""Generate the client config module baked into the frozen tool (D7a = B).

``generate_embed_module`` writes ``_drivedeploy_embed.py`` containing the resolved
deployment config as plain module-level constants. It freezes like any other module
(freezer-agnostic) and the client reads it back via
:mod:`drivedeploy.update.client_config`.
"""

from __future__ import annotations

from pathlib import Path

from drivedeploy.core.config import DriveDeployConfig

EMBED_MODULE_NAME = "_drivedeploy_embed"
_FILENAME = f"{EMBED_MODULE_NAME}.py"

_TEMPLATE = '''"""Generated by drivedeploy. Do not edit by hand.

This module bakes the deployment config into the frozen tool so the bundled
updater can resolve the share, channel, and running version at runtime.
"""

NAME = {name!r}
LOCATION = {location!r}
CHANNEL = {channel!r}
PLATFORM = {platform!r}
KIND = {kind!r}
VERSION = {version!r}
ARTIFACT = {artifact!r}
VERSION_SOURCE = {version_source!r}
'''


def render_embed_module(config: DriveDeployConfig, version: str) -> str:
    """Return the source text of the generated embed module."""
    return _TEMPLATE.format(
        name=config.name,
        location=config.location,
        channel=config.channel,
        platform=config.platform,
        kind=config.kind,
        version=version,
        artifact=config.artifact,
        version_source=config.version_source,
    )


def generate_embed_module(config: DriveDeployConfig, version: str, dest: Path) -> Path:
    """Write the embed module.

    ``dest`` may be a directory (the file is named ``_drivedeploy_embed.py``) or an
    explicit ``.py`` file path. Returns the written path.
    """
    dest = Path(dest)
    target = dest / _FILENAME if dest.is_dir() or not dest.suffix else dest
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_embed_module(config, version), encoding="utf-8")
    return target
